site:
  title: My Docs
  start_page: home:ROOT:index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    # See: https://github.com/stephengold/antora-ui-bundle
    url: https://github.com/stephengold/antora-ui-bundle/releases/download/v-sgold260101a/ui-bundle.zip
    snapshot: true

output:
  dir: ../dist
