## Description


## Setup Instructions

### Repository Structure

[source,plaintext]
----
repo/
├── antora-playbook.yml
├── site/
│   └── ui/ ... the Antora UI files (Optional, can be customized)
└── docs/
    ├── antora.yml
    └── modules/
                ├── nav.adoc
                └── pages
                    └── index.adoc
----

Minimal `antora-playbook.yml` configuration:

[source,yaml]
.antora-playbook.yml
----
site:
  title: My Docs
  start_page: home:ROOT:index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    # See: https://github.com/stephengold/antora-ui-bundle
    url: https://github.com/stephengold/antora-ui-bundle/releases/download/v-sgold260101a/ui-bundle.zip
    snapshot: true

output:
  dir: ../dist
----

[source,yaml]
.docs/antora.yml
----
name: home
version: ~
title: Project Root
nav:
- modules/ROOT/nav.adoc
----

[source,asciidoc]
.docs/modules/ROOT/pages/index.adoc
----
= Welcome!

You are home.

----

[source,asciidoc]
.docs/modules/ROOT/nav.adoc
----
* xref:index.adoc[Home]
----

[source,yaml]
..github/workflows/pages.yml
----
name: Build and Deploy Antora Documentation to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build the site by converting AsciiDoc files to HTML using Asciidoctor
  build:
    runs-on: ubuntu-latest
    name: convert asciidoc to html
    steps:
    # Checkout the repository
    # See: https://github.com/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6

    # See: https://github.com/actions/setup-node
    - name: Install Node
      uses: actions/setup-node@v6.4.0
      with:
        node-version: 24
    - name: Install Antora
      run: npm install -g @antora/cli @antora/site-generator

    - name: Generate site
      working-directory: docs
      run: antora ../antora-playbook.yml

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/

  # Deploy to GitHub Pages
  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
----

## Local Setup for Testing

### Install Node.js and npm

[source,shell]
----
sudo apt install -y nodejs npm
----

. Install `n` to manage Node.js versions:

[source,shell]
----
sudo npm install n -g
----

. Install the latest stable version of Node.js using `n`:
+
[source,shell]
----
sudo n stable
----

// nパッケージの導入により不要になったNode.jsとnpmを削除
. Uninstall the system-installed Node.js and npm, as they are no longer needed:
+
[source,shell]
----
sudo apt purge -y nodejs npm
sudo apt autoremove -y
----

### Install Antora locally

See: https://docs.antora.org/antora/latest/install/install-antora/[Install Antora locally]

Requires Node.js and npm.

. Navigate to the `docs` directory:
+
[source,shell]
----
cd docs
----

. Initialize a new npm project and install Antora CLI as a development dependency:
+
[source,shell]
----
node -e "fs.writeFileSync('package.json', '{}')"
npm i -D -E @antora/cli@3.1
----

. Verify the installation by checking the Antora version:
+
[source,shell]
----
npx antora -v
----

. Install the Antora site generator as a development dependency:
+
[source,shell]
----
npm i -D -E @antora/site-generator@3.1
----

## Build the documentation site
. Run the Antora build command to generate the static site:
+
[source,shell]
----
cd docs
----

. Build the site using the Antora playbook:
+
[source,shell]
----
npx antora ../antora-playbook.yml
----

. The generated site will be located in the `dist` directory as specified in the `antora-playbook.yml` configuration:


### Customize the Antora UI (Optional)

Here is an example of modifications for displaying mathematical equations.

If you only want to verify the local operation, you can make the code changes as shown below to get it working. However, please consider how to incorporate the UI bundle in accordance with the license requirements of the distribution source.

In practice, if you want to customize and distribute the Antora UI, you would download and extract the UI bundle, make the necessary changes, and either include the modified UI bundle in your own repository or host it on a CDN and specify the URL.

[source,shell]
----
wget https://github.com/stephengold/antora-ui-bundle/releases/download/v-sgold260101a/ui-bundle.zip -O ui-bundle.zip
----
. Unzip the downloaded UI bundle and customize the files as needed:
+
[source,shell]
----
unzip ui-bundle.zip -d docs/ui
rm -f ui-bundle.zip
----

Change ui ≫ bundle ≫ url in `antora-playbook.yml` to point to your customized UI bundle.

[source,yml]
.antora-playbook.yml
----
site:
  title: My Docs
  start_page: home:ROOT:index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: ./docs/ui
    snapshot: true

output:
  dir: ../dist
----

[source,javascript]
.docs/ui/antora-ui-default/partials/head-scripts.hbs
----
<script>
window.MathJax = {
  tex: { inlineMath: [['$', '$'], ['\\(', '\\)']] },
  svg: { fontCache: 'global' }
};
</script>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
----
